# Generated by Django 5.1.2 on 2025-08-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hotelvendor_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluser',
            options={'verbose_name': 'Hotel User', 'verbose_name_plural': 'Hotel Users'},
        ),
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={'verbose_name': 'Hotel Vendor', 'verbose_name_plural': 'Hotel Vendors'},
        ),
    ]
