# Generated by Django 5.1.2 on 2025-08-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_hoteluser_options_alter_hotelvendor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={},
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='Hotel Vendors',
        ),
    ]
