# Generated by Django 5.1.2 on 2025-08-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hotelvendor_options_alter_hotelvendor_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='anemeties',
            new_name='ameneties',
        ),
        migrations.RemoveField(
            model_name='ameneties',
            name='image',
        ),
        migrations.AlterField(
            model_name='ameneties',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
