# Generated by Django 5.1.2 on 2025-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_anemeties_hotel_ameneties_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelvendor',
            table='hotel_vendor',
        ),
    ]
