# Generated by Django 5.1.2 on 2025-09-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_hotelbooking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotelvendor',
            table='Hotel Vendors',
        ),
    ]
